#使用配置文件,配置数据
auto:
  field:
    name: chaohl
    title: chaohlDemo
#    参数间引用
    desc: ${auto.field.name}正在做${auto.field.title}
#    生成随机值
    randomValue: ${random.value}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DemoDB?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: lynu.chaohl.SpringbootBaseMybatis.**.mapper
#      # 加载全局的配置文件
#  configLocation: classpath:mybatis/mybatis-config.xml

