## 书信息
demo:
    book:
        name: 《Spring Boot 2.x 核心技术实战 - 上 基础篇》
        writer: 泥瓦匠BYSocket

spring:
 mvc:
  pathmatch:
## 2.6.x版本的spingboot不兼容swagger某些版本,需要添加的配置。
    matching-strategy: ant_path_matcher
 datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT
    username: root
    password: 123456
mybatis:
 mapper-locations: classpath:mapper/*.xml

# 访问示例：http://localhost:9595/monitor
management:
#  security:
#    enabled: false
  endpoints:
    web:
      # actuator的访问路径，替换默认/actuator
      base-path: /monitor
      # 设置是否暴露端点 默认只有health和info可见
      exposure:
        # include: env   # 方式1: 暴露端点env，配置多个以,隔开
        include: "*"     # 方式2: 包括所有端点，注意需要添加引号
        # 排除端点
        exclude: shutdown
  server:
    port: 9595  #新开监控端口，不和应用用同一个端口
  endpoint:
    health:
      show-details: always # 显示db、redis、rabbti连接情况等
    shutdown:
      enabled: true  #默认情况下，除shutdown以外的所有端点均已启用。手动开启
#spring:
# mvc:
#  pathmatch:
### 2.6.x版本的spingboot不兼容swagger某些版本,需要添加的配置。
#    matching-strategy: ant_path_matcher

#  datasource:
#  #mybatis连接配置
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT
#      username: root
#      password: 123456
## H2数据库连接配置、不做配置时、按照默认配置。
#    driver-class-name: org.h2.Driver
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
#        # No restrictions on table names
#    url: jdbc:h2:mem:h2
#        # No restrictions on username and password
#    username: root
#    password: 123
netty:
  websocket:
    # Websocket服务端口
    port: 1024
    # 绑定的网卡
    ip: 0.0.0.0
    # 消息帧最大体积
    max-frame-size: 10240
    # URI路径
    path: /channel
