#使用配置文件,配置数据
auto:
  field:
    name: chaohl
    title: chaohlDemo
#    参数间引用
    desc: ${auto.field.name}正在做${auto.field.title}
#    生成随机值
    randomValue: ${random.value}
propertiesTest: 这是一个swagger的Demo测试!!!
#mybatis默认数据源配置

spring:
 # 数据源配置
  datasource:
    default: #数据源1
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/DemoDB?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: root
      password: 123456
      #数据库连接池配置，采用druid
      type: com.alibaba.druid.pool.DruidDataSource

    master:
      url: jdbc:mysql://localhost:3306/demodb_cluster?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

#mongodb配置
  data:
    mongodb:
      host: localhost
      database: mongoDBTest
      port: 27017
      username: root
      password: root




cluster:
  datasource:
    url: jdbc:mysql://localhost:3306/demodb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

file:
  size:
    limit: 50MB

#远程调用第三方的接口
feign:
  client:
    url: http://192.168.1.100:5800/HCenter1



