#使用配置文件,配置数据
auto:
  field:
    name: chaohl
    title: chaohlDemo
#    参数间引用
    desc: ${auto.field.name}正在做${auto.field.title}
#    生成随机值
    randomValue: ${random.value}
propertiesTest: 这是一个swagger的Demo测试!!!
#mybatis默认数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DemoDB?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456

#数据库连接池配置，采用druid
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #  通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

#mongodb配置
  data:
    mongodb:
      host: localhost
      database: mongoDBTest
      port: 27017
      username: root
      password: root


#主从库测试中的主库配置
master:
  datasource:
    url: jdbc:mysql://localhost:3306/demodb_cluster?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver


cluster:
  datasource:
    url: jdbc:mysql://localhost:3306/demodb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

# MyBatis
#mybatis:
    # 搜索指定包别名
#    typeAliasesPackage: com.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
#    mapperLocations: classpath*:mybatis/**/*Mapper.xml, classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
#    configLocation: classpath:mybatis/mybatis-config.xml

file:
  size:
    limit: 50MB

#远程调用第三方的接口
feign:
  client:
    url: http://192.168.1.100:5800/HCenter1



